/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // Design system colors from Volt X design
        "on-primary-container": "#768dad",
        "surface-container-highest": "#e0e3e6",
        "secondary-fixed-dim": "#ffb59d",
        "tertiary-fixed": "#ffdcbe",
        "background": "#f7f9fc",
        "primary-container": "#0a2540",
        "surface": "#f7f9fc",
        "outline": "#74777e",
        "secondary": "#ab3500",
        "secondary-fixed": "#ffdbd0",
        "on-error-container": "#93000a",
        "on-primary": "#ffffff",
        "inverse-surface": "#2d3133",
        "surface-variant": "#e0e3e6",
        "on-error": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#314865",
        "error": "#ba1a1a",
        "on-tertiary-container": "#ae835a",
        "inverse-on-surface": "#eff1f4",
        "tertiary-container": "#381d00",
        "on-secondary-fixed": "#390c00",
        "primary-fixed-dim": "#b0c8eb",
        "secondary-container": "#fe6a34",
        "surface-container-high": "#e6e8eb",
        "on-background": "#191c1e",
        "outline-variant": "#c4c6ce",
        "on-surface": "#191c1e",
        "on-tertiary": "#ffffff",
        "primary": "#000f22",
        "tertiary-fixed-dim": "#eebd90",
        "surface-dim": "#d8dadd",
        "on-surface-variant": "#43474d",
        "primary-fixed": "#d2e4ff",
        "surface-container-low": "#f2f4f7",
        "inverse-primary": "#b0c8eb",
        "error-container": "#ffdad6",
        "on-secondary-container": "#5d1900",
        "surface-bright": "#f7f9fc",
        "on-tertiary-fixed-variant": "#613f1c",
        "on-secondary": "#ffffff",
        "surface-container": "#eceef1",
        "on-tertiary-fixed": "#2d1600",
        "on-primary-fixed": "#001c37",
        "surface-tint": "#49607e",
        "tertiary": "#1a0b00",
        "on-secondary-fixed-variant": "#832600",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "1rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
